# Generated by Django 2.2.2 on 2019-06-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_to_cart',
        ),
    ]
