# Generated by Django 2.2.2 on 2019-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
