# Generated by Django 2.2.2 on 2019-06-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ident',
            field=models.CharField(default='random', max_length=30),
        ),
    ]
