# Generated by Django 2.2.2 on 2019-06-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_product_ident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_ident',
        ),
    ]
